// Figma layers exported from the Lawnalyze UI zips, with their 1x design sizes (the
// design frame is 340pt wide). Positions for each layer live in the screen files.

export type UiAsset = { source: number; w: number; h: number };

export const ui = {
  common: {
    box115x85: { source: require('../../assets/ui/common/box-115x85.png'), w: 115, h: 85 },
    box160x85: { source: require('../../assets/ui/common/box-160x85.png'), w: 160, h: 85 },
    cardBottom: { source: require('../../assets/ui/common/card-bottom.png'), w: 340, h: 87 },
    footerGreen: { source: require('../../assets/ui/common/footer-green.png'), w: 340, h: 176 },
    glowTall: { source: require('../../assets/ui/common/glow-tall.png'), w: 432, h: 537 },
    glowWide: { source: require('../../assets/ui/common/glow-wide.png'), w: 492, h: 475 },
    glow: { source: require('../../assets/ui/common/glow.png'), w: 432, h: 475 },
    gradient: { source: require('../../assets/ui/common/gradient.png'), w: 340, h: 454 },
    iconBox: { source: require('../../assets/ui/common/icon-box.png'), w: 34, h: 34 },
    inputAddress: { source: require('../../assets/ui/common/input-address.png'), w: 270, h: 38 },
    inputCity: { source: require('../../assets/ui/common/input-city.png'), w: 172, h: 38 },
    inputState: { source: require('../../assets/ui/common/input-state.png'), w: 82, h: 38 },
    labelPerWeek: { source: require('../../assets/ui/common/label-per-week.png'), w: 65, h: 14 },
    labelPerYear: { source: require('../../assets/ui/common/label-per-year.png'), w: 58, h: 12 },
    labelAddress: { source: require('../../assets/ui/common/label-address.png'), w: 52, h: 10 },
    labelCity: { source: require('../../assets/ui/common/label-city.png'), w: 25, h: 13 },
    labelState: { source: require('../../assets/ui/common/label-state.png'), w: 33, h: 10 },
    logoSmall: { source: require('../../assets/ui/common/logo-small.png'), w: 156, h: 29.7 },
    logo: { source: require('../../assets/ui/common/logo.png'), w: 280.5, h: 53.4 },
    navDot: { source: require('../../assets/ui/common/nav-dot.png'), w: 7, h: 7 },
  },
  footage: {
    boxFootage: { source: require('../../assets/ui/footage/box-footage.png'), w: 292, h: 89 },
    btnConfirmSquareFootage: { source: require('../../assets/ui/footage/btn-confirm-square-footage.png'), w: 243, h: 44 },
    iconRuler: { source: require('../../assets/ui/footage/icon-ruler.png'), w: 42, h: 28 },
    labelYourLawnIs: { source: require('../../assets/ui/footage/label-your-lawn-is.png'), w: 94, h: 12 },
    titleLawnSquareFootage: { source: require('../../assets/ui/footage/title-lawn-square-footage.png'), w: 198, h: 20 },
  },
  home: {
    boxLawn: { source: require('../../assets/ui/home/box-lawn.png'), w: 120, h: 68 },
    boxWeather: { source: require('../../assets/ui/home/box-weather.png'), w: 286, h: 85 },
    labelSquareFeet: { source: require('../../assets/ui/home/label-square-feet.png'), w: 82, h: 15 },
    navHome: { source: require('../../assets/ui/home/nav-home.png'), w: 304, h: 26 },
    textRainHint: { source: require('../../assets/ui/home/text-rain-hint.png'), w: 277, h: 21 },
    titleSquareFootage: { source: require('../../assets/ui/home/title-square-footage.png'), w: 224, h: 16 },
    titleWaterAndCost: { source: require('../../assets/ui/home/title-water-and-cost.png'), w: 186, h: 12 },
    titleWeather: { source: require('../../assets/ui/home/title-weather.png'), w: 158, h: 15 },
  },
  intro: {
    n2026: { source: require('../../assets/ui/intro/2026.png'), w: 74, h: 23 },
    btnGetStarted: { source: require('../../assets/ui/intro/btn-get-started.png'), w: 243, h: 44 },
    lawnWaterEstimator: { source: require('../../assets/ui/intro/lawn-water-estimator.png'), w: 170, h: 64 },
    meetTheWorldsFirst: { source: require('../../assets/ui/intro/meet-the-worlds-first.png'), w: 223, h: 60 },
    savingWater: { source: require('../../assets/ui/intro/saving-water.png'), w: 177, h: 30 },
    since: { source: require('../../assets/ui/intro/since.png'), w: 72, h: 23 },
    throughSatelite: { source: require('../../assets/ui/intro/through-satelite.png'), w: 218, h: 30 },
  },
  locate: {
    btnFindMyLawn: { source: require('../../assets/ui/locate/btn-find-my-lawn.png'), w: 243, h: 44 },
    iconLocate: { source: require('../../assets/ui/locate/icon-locate.png'), w: 34, h: 34 },
    titleLocateYourLawn: { source: require('../../assets/ui/locate/title-locate-your-lawn.png'), w: 160, h: 19 },
  },
  mark: {
    btnMarkMyLawn: { source: require('../../assets/ui/mark/btn-mark-my-lawn.png'), w: 243, h: 44 },
    iconPencil: { source: require('../../assets/ui/mark/icon-pencil.png'), w: 18, h: 18 },
    titleMarkYourLawn: { source: require('../../assets/ui/mark/title-mark-your-lawn.png'), w: 145, h: 19 },
    toolCircle: { source: require('../../assets/ui/mark/tool-circle.png'), w: 28, h: 28 },
    toolPencil: { source: require('../../assets/ui/mark/tool-pencil.png'), w: 25, h: 25 },
    toolPill: { source: require('../../assets/ui/mark/tool-pill.png'), w: 28, h: 53 },
    toolPlus: { source: require('../../assets/ui/mark/tool-plus.png'), w: 16, h: 20 },
    toolTrash: { source: require('../../assets/ui/mark/tool-trash.png'), w: 28, h: 28 },
  },
  rebates: {
    boxBest: { source: require('../../assets/ui/rebates/box-best.png'), w: 295, h: 112 },
    boxOther: { source: require('../../assets/ui/rebates/box-other.png'), w: 295, h: 87 },
    labelBestChoice: { source: require('../../assets/ui/rebates/label-best-choice.png'), w: 86, h: 12 },
    labelOtherChoices: { source: require('../../assets/ui/rebates/label-other-choices.png'), w: 108, h: 12 },
    navRebates: { source: require('../../assets/ui/rebates/nav-rebates.png'), w: 304, h: 26 },
    titleRebates: { source: require('../../assets/ui/rebates/title-rebates.png'), w: 151, h: 15 },
  },
  settings: {
    boxEditPanel: { source: require('../../assets/ui/settings/box-edit-panel.png'), w: 130, h: 77 },
    boxPanel: { source: require('../../assets/ui/settings/box-panel.png'), w: 295, h: 119 },
    navSettings: { source: require('../../assets/ui/settings/nav-settings.png'), w: 304, h: 26 },
    rowEditLawn: { source: require('../../assets/ui/settings/row-edit-lawn.png'), w: 113, h: 30 },
    rowSelected: { source: require('../../assets/ui/settings/row-selected.png'), w: 272, h: 30 },
    rowShowDimensions: { source: require('../../assets/ui/settings/row-show-dimensions.png'), w: 113, h: 30 },
    rowUnselected: { source: require('../../assets/ui/settings/row-unselected.png'), w: 272, h: 30 },
    textEditLawn: { source: require('../../assets/ui/settings/text-edit-lawn.png'), w: 51, h: 9 },
    textNoThanks: { source: require('../../assets/ui/settings/text-no-thanks.png'), w: 58, h: 9 },
    textShowDimensions: { source: require('../../assets/ui/settings/text-show-dimensions.png'), w: 94, h: 9 },
    textWeatherEvents: { source: require('../../assets/ui/settings/text-weather-events.png'), w: 188, h: 10 },
    titleMeasurement: { source: require('../../assets/ui/settings/title-measurement.png'), w: 190, h: 12 },
    titleNotifications: { source: require('../../assets/ui/settings/title-notifications.png'), w: 91, h: 12 },
    titleSettings: { source: require('../../assets/ui/settings/title-settings.png'), w: 58, h: 15 },
  },
  usage: {
    box115x70: { source: require('../../assets/ui/usage/box-115x70.png'), w: 115, h: 70 },
    boxDrop: { source: require('../../assets/ui/usage/box-drop.png'), w: 160, h: 152 },
    labelPerWeekSmall: { source: require('../../assets/ui/usage/label-per-week-small.png'), w: 57, h: 13 },
    labelPerYearSmall: { source: require('../../assets/ui/usage/label-per-year-small.png'), w: 51, h: 10 },
    labelUsage: { source: require('../../assets/ui/usage/label-usage.png'), w: 74, h: 22 },
    navUsage: { source: require('../../assets/ui/usage/nav-usage.png'), w: 304, h: 26 },
    textUnitsHint: { source: require('../../assets/ui/usage/text-units-hint.png'), w: 271, h: 23 },
    titleComparison: { source: require('../../assets/ui/usage/title-comparison.png'), w: 261, h: 15 },
    titleWaterCost: { source: require('../../assets/ui/usage/title-water-cost.png'), w: 155, h: 12 },
    titleWaterUsage: { source: require('../../assets/ui/usage/title-water-usage.png'), w: 167, h: 15 },
    waterDrop: { source: require('../../assets/ui/usage/water-drop.png'), w: 132, h: 132 },
  },
  welcome: {
    back: { source: require('../../assets/ui/welcome/back.png'), w: 72, h: 26 },
    btnContinue: { source: require('../../assets/ui/welcome/btn-continue.png'), w: 243, h: 44 },
    mate: { source: require('../../assets/ui/welcome/mate.png'), w: 76, h: 21 },
    readyTo: { source: require('../../assets/ui/welcome/ready-to.png'), w: 119, h: 28 },
    saving: { source: require('../../assets/ui/welcome/saving.png'), w: 103, h: 30 },
    start: { source: require('../../assets/ui/welcome/start.png'), w: 64, h: 21 },
    welcome: { source: require('../../assets/ui/welcome/welcome.png'), w: 129, h: 22 },
  },
} satisfies Record<string, Record<string, UiAsset>>;
